### ISSUE TITLE
copying robomong.json from windows to mac os x not including ssh

### ISSUE THREAD

**Issue by lesterjanpearson** [Studio3T/robomongo#1271]
when I copied the robomongo.json files to mac, it didnt include the ssh credentials.

**Comment by juliashibalko** [comment]
Hi @lesterjanpearson,
Could you please add issue steps and any details that will help us with investigation?
SSH credentials are saved only after successful connection. Also please verify checkbox "Ask for password/passphrase each time" is not ticked. Otherwise password won't be stored in `.config` file.
Do you have the same Robomongo versions on computers?

Thanks in advance!

**Comment by juliashibalko** [comment]
Checked under Win 7, 10; Mac OS X 10.11, 10.12. Can't reproduce the issue. Closing as can't reproduce. 
Feel free to re-open in any case.
