### ISSUE TITLE
mongodb atlas - with authdatabase NOT admin

### ISSUE THREAD

**Issue by redimongo** [Studio3T/robomongo#1272]
I am having a huge issue connecting to a collection that I need to connect to an the only way to do so is via the following which works fine when I am connecting via PHP but, your app does not allow me to set custom options.

`?ssl=true&sslWeakCertificateValidation=true`

I have tried to set it to self-sign cert with no success.

Please advise.

**Comment by simsekgokhan** [comment]
Hi @redimongo , thanks for reporting the problem.

From SSL point of view, Robomongo supports all the advanced options (except FIPS mode) which **mongo (client)** supports. ( run "mongo -h" and see ssl options). 

The flag you wrote is a **mongod (server)** flag not a client:

```
mongod -h
  ...
  --sslWeakCertificateValidation        allow client to connect without presenting a certificate
```

Back to the problem, I suspect your problem might be related to user & permissions.
We will investigate. 

In order to reproduce your problem, can you share the following details please?
- Error details, a screenshot will be helpful
- Connection settings, again screenshots of settings tabs will be helpful
- Robomongo and local OS versions

Best Regards.

**Comment by juliashibalko** [comment]
Hi @redimongo! Could you please check issue with Robo3T 1.1 if possible? Also please share results and info to help us with reproducing the problem.
Please see new release here https://robomongo.org/download.

**Comment by prem911** [comment]
Facing similar issues.
Using admin, I m able to login in Robo 3T 1.1 for mongo Atlas cluster.
However the login fails with other db users. I have given "readWrite" role to couple of users for specific DB.

In Mongo Compass, I was able to login as all users ( admin and specific users )

**Comment by lukasvosyka** [comment]
Any news on this?

**Comment by redimongo** [comment]
Sorry we have moved away from using atlas and now run our own cluster servers
