### ISSUE TITLE
robomongo 连接mongodb报 Authorization failed  错误

### ISSUE THREAD

**Issue by wordhui** [Studio3T/robomongo#1324]
![1](https://cloud.githubusercontent.com/assets/19604635/25119280/18208944-244c-11e7-9805-af5b91a148e3.png)
连接不上 一直报这个错误  查了许多资料 
 大多数  博客上的解决方式是这样的  http://liyanjie918.blog.163.com/blog/static/2022729020156261410274/
但我无法删除admin用户      哈哈 没办法 我再去查资料

**Comment by simsekgokhan** [comment]
Hi @huilaoda , would it be possible to re-write to the ticket in English, please? 
It will be much more easy to make progress : )

**Comment by tericky** [comment]
Help translate in English.

[Image]
Can't connect. Always show this error message like above image.
I look up many solutions on the internet, most likely way people use is: 
[http://liyanjie918.blog.163.com/blog/static/2022729020156261410274/](http://liyanjie918.blog.163.com/blog/static/2022729020156261410274/)

But I still can't delete the admin user. Ha Ha... try to find for more solutions on the internet.

**Comment by simsekgokhan** [comment]
Can you specify OS, Robomongo and mongodb versions please?

The error is related to db user/password error. Please double check your db user/password.
I strongly suggest to create db users on mongo shell (or Robomongo shell). I also suggest to try to connect with mongo shell (i.e. for Windows using C:\Program Files\MongoDB\Server\3.2\bin\mongo.exe) in order to understand if the problem is related to Robomongo or not.

**Comment by juliashibalko** [comment]
Hi @huilaoda, could you please share if issue still exists and add any info that will help us with investigation? 
Please see new release here https://robomongo.org/download.
