### ISSUE TITLE
Ability to create Connection from URL

### ISSUE THREAD

**Issue by wowkin2** [Studio3T/robomongo#1329]
Hi, it would be great to have ability to create new connection from URL:
`mongodb://<username>:<password>@<address>:<port>/<auth_database>`
just copy-pasting it for example from mLab config.

It can be just one more button in Connection Settings dialog, that show prompt and fill required fields from url typed there.

**Comment by simsekgokhan** [comment]
Hi @wowkin2 , thanks for your interest in Robomongo. We actually developed most of this feature but could not finish due to some reasons. I hope we will continue and finish this feature soon. You can track progress here: https://github.com/Studio3T/robomongo/issues/600

I will close this ticket as duplicate now, feel free to reopen for any reason.
