### ISSUE TITLE
page navigation is not coming when we do aggregation query , it is coming when we do find query

### ISSUE THREAD

**Issue by prashantp995** [Studio3T/robomongo#1361]
db.getCollection('movieDetails').aggregate([
{$group: {  _id: {"director": "$director","title":"$title"}}}
])
![image](https://cloud.githubusercontent.com/assets/17299110/26445686/7893a232-415e-11e7-8b50-68c9a60334b8.png)

**Comment by juliashibalko** [comment]
@prashantp995 thanks for reporting! It's known issue and we're sorry for that! Issue'll be fixed in the further releases.
As a workaround please check the tips from the ticket #1058 here https://github.com/Studio3T/robomongo/issues/1058#issuecomment-203305989. Hope they will help you!
Also let me suggest you to track fixing progress with the same #1058 card. So I will close current ticket as duplicate if you don't mind.

**Comment by simsekgokhan** [comment]
Hi @prashantp995 , sorry for the long delay, this issue should be fixed in Robo 3T 1.2.
Please see: https://blog.robomongo.org/robo-3t-1-2/#a2
