### ISSUE TITLE
Connecting to same replica set cluster

### ISSUE THREAD

**Issue by rubilnikas** [Studio3T/robomongo#1400]
I have several clusters for different development environments and if I try to open connections for other clusters connecting to the same cluster not configured in connection.
**Connection for second cluster:**
![same cluster 2](https://user-images.githubusercontent.com/11923690/27785349-faed92ba-5fe5-11e7-89bb-004647881bd4.jpg)
**After conecting to same first and second cluster:**
![same cluster](https://user-images.githubusercontent.com/11923690/27785370-10123c18-5fe6-11e7-9f70-8d8d31b1fa18.jpg)

**Comment by simsekgokhan** [comment]
Hi @rubilnikas , thanks for reporting the problem.

Firstly, do you have same set name for your different clusters?
If this is your case, there is a known limitation and a critical related problem fixed in version 1.0.
Details here: Section `c. Bug fixes -> i. Fix to avoid the same set name problem`: http://blog.robomongo.org/robomongo-1-0/

I strongly suggest to use latest version https://robomongo.org/download.
The solution for now is to open a new instance of program for each cluster with same set name.

Hope this is your problem and it helps.

**Comment by rubilnikas** [comment]
Thanks for the response. Yes, I have the same set name for different clusters. Will use a workaround with new program instance, for now. Hope this will be fixed soon.
