### ISSUE TITLE
I can't update the function

### ISSUE THREAD

**Issue by javalipengfei** [Studio3T/robomongo#1492]
i update the function, i click the save button, but i found it can't save when i reopen it ,

**Comment by juliashibalko** [comment]
@javalipengfei  thanks for submitting the issue! 
Experienced the same one.
STR:
1. Click "Edit function", update function name and save.
Actual result: new function with updated name is created instead of saving edited function.

2. Click "Edit function", update function code and save.
Actual result: nothing is saved after submitting.

**Comment by simsekgokhan** [comment]
@javalipengfei. Feel free to re-open if you still have the problem with latest version.
