### ISSUE TITLE
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos

### ISSUE THREAD

**Issue by roberto68** [Studio3T/robomongo#1553]
I start robo3t from command line this is what I get 
`
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected

`

**Comment by cameroncan** [comment]
I'm experiencing the same thing and it results in an unusable white screen

**Comment by xGanimeDx** [comment]
@roberto68 @cameroncan possibly this will work for you https://stackoverflow.com/questions/26361145/qsslsocket-error-when-ssl-is-not-used
There is nothing serious at first sight, just warnings which should not affect you

**Comment by simsekgokhan** [comment]
Hi All, thanks for reporting the problem. Robo supports Ubuntu 18.04 from version 1.3.
Can you please try our beta? We have some related code changes which can fix your problem.

@roberto68 Those logs can be ignored, they are produced all the time. Can you give details what your problem is exactly?

Robo 3T 1.3 Beta
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

**Comment by simsekgokhan** [comment]
Robo 3T 1.3 Beta with Ubuntu 18.04 support, has been updated with more changes. 
https://github.com/Studio3T/robomongo/releases/tag/v1.3.0-beta

Feel free to open the ticket if you find problem again.
