### ISSUE TITLE
Unable to connect after MacOS Catalina Update

### ISSUE THREAD

**Issue by ShakMR** [Studio3T/robomongo#1713]
After upgrading to MacOS Catalina the configured connections to AWS DocumentDB broke as the CA was been revoked. See image below
![Screenshot 2020-02-25 at 12 06 40](https://user-images.githubusercontent.com/3437307/75242892-3ce67280-57c9-11ea-8585-d235dbdb034d.png)

After adding the certificate to the key chain and trusting it manually it seems that I can connect from the command line and use `mongoexport` `mongoimport` correctly that makes me think that something is not right with Robo3t. May be no access to key chain from Robo3t?

Is there any new version of the app coming with anything in specific for MacOS Catalina?

Robo 3T 1.3.1
OS - macOS Catalina (10.15.3)

**Comment by BeeShall** [comment]
Having the same exact problem

**Comment by ShakMR** [comment]
We solved this in the team by downgrading Robo3T to 1.2.1

**Comment by BeeShall** [comment]
@ShakMR I have a solution for you! After a week of digging into what the issue was, I finally know what is happening.

Looks like macOS Catalina did something with their CA certs thing so that your CA bundle (rds-ca-bundle) is no longer trusted. So, in the SSL section, if you select the Authentication Method to be Self Signed Certificate, your issue will be solved.

**Comment by ShakMR** [comment]
Hey @BeeShall that worked fine 😄 we can probably close this issue then.
